USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FILE FORMAT SNOWFLAKE_LEARNING_DB.PUBLIC.MY_PARQUET_FORMAT
  TYPE = PARQUET;

CREATE OR REPLACE STAGE SNOWFLAKE_LEARNING_DB.PUBLIC.TAXI_HOURLY_ZONE_STAGE
  URL = 'gcs://msba405-nyc-project/processed/taxi_hourly_zone/nyc_hourly_zone_final/'
  STORAGE_INTEGRATION = GCS_INT
  FILE_FORMAT = SNOWFLAKE_LEARNING_DB.PUBLIC.MY_PARQUET_FORMAT;

CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.NYC_HOURLY_ZONE_FINAL_GCS (
  hour_ts TIMESTAMP_NTZ,
  locationid INTEGER,
  borough STRING,
  zone STRING,
  service_zone STRING,
  trips INTEGER,
  avg_fare_amount FLOAT,
  avg_tip_amount FLOAT,
  avg_total_amount FLOAT,
  avg_trip_distance FLOAT
);

COPY INTO SNOWFLAKE_LEARNING_DB.PUBLIC.NYC_HOURLY_ZONE_FINAL_GCS
FROM @SNOWFLAKE_LEARNING_DB.PUBLIC.TAXI_HOURLY_ZONE_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\.parquet';

CREATE OR REPLACE VIEW SNOWFLAKE_LEARNING_DB.PUBLIC.V_NYC_HOURLY_ZONE_FINAL AS
SELECT
    hour_ts,
    locationid,
    borough,
    zone,
    service_zone,
    trips,
    avg_fare_amount,
    avg_tip_amount,
    avg_total_amount,
    avg_trip_distance
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.NYC_HOURLY_ZONE_FINAL_GCS;