
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW nyc_hourly_borough_TABLEAU AS
SELECT
    YEAR,
    MONTH,
    DAY::NUMBER AS DAY,
    HOUR::NUMBER AS HOUR,
    TO_TIMESTAMP(HOUR_TS::STRING) AS HOUR_TS,
    BOROUGH,
    TRIPS::NUMBER AS TRIPS,
    AVG_FARE_AMOUNT::FLOAT AS AVG_FARE_AMOUNT,
    AVG_TIP_AMOUNT::FLOAT AS AVG_TIP_AMOUNT,
    AVG_TOTAL_AMOUNT::FLOAT AS AVG_TOTAL_AMOUNT,
    AVG_TRIP_DISTANCE::FLOAT AS AVG_TRIP_DISTANCE,
    AVG_TRIP_DURATION_MIN::FLOAT AS AVG_TRIP_DURATION_MIN,
    TEMP_AVG::FLOAT AS TEMP_AVG,
    DEWPOINT_AVG::FLOAT AS DEWPOINT_AVG,
    HUMIDITY_AVG::FLOAT AS HUMIDITY_AVG,
    WIND_AVG::FLOAT AS WIND_AVG,
    WIND_GUST_AVG::FLOAT AS WIND_GUST_AVG,
    PRESSURE_AVG::FLOAT AS PRESSURE_AVG,
    PRECIP_TOTAL::FLOAT AS PRECIP_TOTAL,
    SNOW_TOTAL::FLOAT AS SNOW_TOTAL,
    SNOW_TEXT,
    SNOW_CODE,
    SNOW,
    RAIN,
    RAIN_CODE,
    RAIN_TEXT,
    EXTREME_WEATHER,
    COMPLAINTS_311,
    COMPLAINTS_NOISE,
    COMPLAINTS_SANITATION,
    COMPLAINTS_TRANSPORTATION,
    SOURCE_FILE
FROM nyc_hourly_borough_final;